[package]
name = "rfem"
version = "0.1.0"
authors = ["shinichi <t-shin-komae>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
